import { readFileSync, readdirSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

const script = readFileSync(new URL("../script.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../styles.css", import.meta.url), "utf8");
const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const packageJson = readFileSync(new URL("../package.json", import.meta.url), "utf8");
const customNode = readFileSync(new URL("../custom-nodes/YuntiAiSalesModule.node.js", import.meta.url), "utf8");
const customNodeFiles = readdirSync(new URL("../custom-nodes", import.meta.url)).filter((file) => file.endsWith(".node.js"));

test("n8n page keeps native n8n canvas as the primary surface", () => {
  assert.match(script, /businessNodeCatalog/);
  assert.match(script, /飞书消息入口/);
  assert.match(script, /AI识别销售意图/);
  assert.match(script, /转人工/);
  assert.match(script, /n8n-native-crop/);
  assert.match(script, /n8nFrontendMirrorMode = true/);
  assert.match(script, /n8nMirrorWorkflow/);
  assert.match(script, /renderN8nMirrorFrame/);
  assert.match(script, /n8n-mirror-node-panel/);
  assert.match(script, /前端镜像模式/);
  assert.match(script, /搜索“AI销售 模块”/);
  assert.match(script, /AI销售模块/);
  assert.doesNotMatch(script, />人工审核</);
  assert.doesNotMatch(script, /Human in the Loop/);
  assert.doesNotMatch(script, /<iframe id="n8nUiFrame"/);
  assert.doesNotMatch(script, /<aside class="yunti-workflow-side">/);
  assert.doesNotMatch(script, /business-canvas-panel/);
  assert.doesNotMatch(script, /n8n-native-crop collapsed/);
  assert.doesNotMatch(script, /\$\{renderBusinessWorkbench\(\)\}/);
  assert.match(styles, /\.n8n-native-crop\s*\{\s*position: relative;/);
  assert.match(styles, /\.n8n-mirror-app/);
  assert.match(styles, /\.n8n-mirror-node-panel/);
  assert.match(styles, /\.page-view:has\(.n8n-ui-panel\) \.yunti-workflow-main > header/);
  assert.match(styles, /\.page-view:has\(.n8n-ui-panel\) \.n8n-business-workbench/);
});

test("local n8n loads the AI sales business module node package", () => {
  assert.match(packageJson, /N8N_CUSTOM_EXTENSIONS=\.\/custom-nodes/);
  assert.ok(customNodeFiles.length >= 10);
  assert.match(customNode, /YuntiAiSalesModule/);
  assert.match(customNode, /AI销售 模块｜模块执行器/);
  assert.match(customNode, /categories: \["AI销售 模块"\]/);
  assert.match(customNode, /moduleId/);
  assert.match(customNode, /rag-course/);
  assert.match(customNode, /playbook-match/);
  assert.ok(customNodeFiles.includes("YuntiRagCourse.node.js"));
  assert.ok(customNodeFiles.includes("YuntiSalesIntent.node.js"));
  assert.ok(customNodeFiles.includes("YuntiHandoff.node.js"));
  for (const file of customNodeFiles) {
    const source = readFileSync(new URL(`../custom-nodes/${file}`, import.meta.url), "utf8");
    assert.match(source, /displayName: "AI销售 模块/);
    assert.match(source, /categories: \["AI销售 模块"\]/);
  }
});

test("AI helper frames natural-language SOP edits around business nodes and native n8n fallback", () => {
  assert.match(script, /优先修改云梯智客业务节点|优先使用/);
  assert.match(script, /业务节点不够时调用 n8n 原生节点|n8n 原生/);
  assert.match(script, /新建 SOP/);
  assert.match(script, /原生节点中文对照/);
});

test("AI helper can compile natural language into n8n workflow node patches", () => {
  const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
  assert.match(server, /fetchOpenAi/);
  assert.match(server, /getOpenAiProxyUrl/);
  assert.match(server, /ProxyAgent/);
  assert.match(server, /yunti_compile_sales_sop/);
  assert.match(server, /yunti_patch_workflow_nodes/);
  assert.match(server, /compileSalesSopToNodes/);
  assert.match(server, /applyWorkflowNodePatch/);
  assert.match(server, /upsertWorkflowNodes/);
  assert.match(server, /mergeWorkflowNode/);
  assert.match(server, /getIncomingNodeKeys/);
  assert.match(server, /protectedKeys/);
  assert.match(server, /updatedNodes/);
  assert.match(server, /addedNodes: updated\.addedNodes \|\| \[\]/);
  assert.match(server, /用户点名某个已有节点/);
  assert.match(server, /若 id 或 name 匹配已有节点，则更新原节点而不是新增/);
  assert.match(server, /PUT/);
  assert.match(server, /n8n-nodes-base\.webhook/);
  assert.match(server, /n8n-nodes-base\.if/);
  assert.match(server, /投诉\/价格特批判断/);
  assert.match(server, /yuntiFeishuMessageEntry/);
  assert.match(server, /yuntiFollowupWait/);
  assert.match(server, /yuntiHandoff/);
  assert.match(script, /loadN8nLiveData\(data\.workflowId/);
  assert.match(script, /forceReload/);
  assert.match(script, /_yuntiRefresh/);
  assert.match(script, /frame\.src = "about:blank"/);
  assert.match(script, /new URLSearchParams\(location\.search\)\.get\("workflowId"\)/);
  assert.match(script, /toolResults/);
  assert.doesNotMatch(server, /active:\s*false,/);
});

test("AI helper persists chat history, pending state, and workflow context across refreshes", () => {
  assert.match(script, /AI_MCP_STORAGE_KEY/);
  assert.match(script, /AI_MCP_ACTIVE_SESSION_KEY/);
  assert.match(script, /AI_MCP_PENDING_KEY/);
  assert.match(script, /localStorage\.getItem\(AI_MCP_STORAGE_KEY\)/);
  assert.match(script, /localStorage\.setItem\(AI_MCP_STORAGE_KEY/);
  assert.match(script, /aiMcpSessions/);
  assert.match(script, /aiMcpActiveSessionId/);
  assert.match(script, /createAiMcpSession/);
  assert.match(script, /switchAiMcpSession/);
  assert.match(script, /getActiveAiMcpSession/);
  assert.match(script, /data-ai-mcp-new-chat/);
  assert.match(script, /data-ai-mcp-history-toggle/);
  assert.match(script, /data-ai-mcp-session-menu/);
  assert.match(script, /compactAiMcpSessionTitle/);
  assert.match(script, /data-ai-mcp-session/);
  assert.match(script, /ai-mcp-session-list/);
  assert.match(script, /slice\(0, 8\)/);
  assert.doesNotMatch(script, /formatAiMcpSessionTime/);
  assert.doesNotMatch(script, /<div class="ai-mcp-session-list" id="aiMcpSessionList"><\/div>/);
  assert.match(script, /saveAiMcpState/);
  assert.match(script, /loadAiMcpState/);
  assert.match(script, /setAiMcpPendingState/);
  assert.match(script, /clearAiMcpPendingState/);
  assert.match(script, /getActiveN8nWorkflowId/);
  assert.match(script, /workflowId:\s*getActiveN8nWorkflowId\(\)/);
  assert.match(script, /上次请求未完成/);
  assert.match(script, /isTransientAiMcpConnectionError/);
  assert.doesNotMatch(script, /history\.replaceState\(null, "", "#n8n"\)/);
});

test("AI workflow edits target the current canvas instead of creating a new workflow", () => {
  const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
  assert.match(script, /activeButton\?\.dataset\?\.n8nWorkflow/);
  assert.match(script, /syncN8nWorkflowUrl/);
  assert.match(script, /loadN8nLiveData\(n8nWorkflowButton\.dataset\.n8nWorkflow/);
  assert.match(server, /applyCurrentWorkflowContextToToolArgs/);
  assert.match(server, /getWorkflowIdFromReferer/);
  assert.match(server, /currentWorkflowId/);
  assert.match(server, /name === "yunti_compile_sales_sop"/);
  assert.match(server, /name === "yunti_patch_workflow_nodes"/);
  assert.match(server, /allowNewWorkflow/);
  assert.match(server, /applyCurrentWorkflowContextToToolArgs\(originalName, args, currentWorkflowId, latestUserText, \{ allowNewWorkflow \}\)/);
  assert.match(server, /_allowNewWorkflow/);
  assert.match(server, /Creating a new workflow is disabled for this request/);
  assert.match(server, /refusing to create a new canvas/);
  assert.match(server, /sanitizeWorkflowSettings/);
  assert.doesNotMatch(server, /settings:\s*editable\.settings/);
  assert.match(server, /除非前端显式传入 allowNewWorkflow/);
  assert.match(server, /不要调用 yunti_create_workflow/);
  assert.match(server, /redirectedFrom: name/);
  assert.doesNotMatch(server, /function isExplicitNewWorkflowRequest/);
  assert.doesNotMatch(server, /isExplicitNewWorkflowRequest\(userText\)/);
  assert.doesNotMatch(server, /return \/新建\|/);
});

test("AI helper uses an animated buffer and streams assistant output", () => {
  const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
  assert.match(script, /Accept": "text\/event-stream"/);
  assert.match(script, /readAiMcpStream/);
  assert.match(script, /aiMcpStreamingMessage/);
  assert.match(script, /aiMcpStatusText/);
  assert.match(script, /eventName === "status"/);
  assert.match(script, /ai-mcp-buffer/);
  assert.match(script, /response\.body\.getReader\(\)/);
  assert.match(server, /writeSse/);
  assert.match(server, /openaiResponsesStream/);
  assert.match(server, /flushHeaders/);
  assert.match(server, /response\.output_text\.delta/);
  assert.match(server, /writeSse\(res, "done"/);
  assert.match(styles, /\.ai-mcp-buffer/);
  assert.match(styles, /@keyframes aiMcpBufferPulse/);
  assert.doesNotMatch(script, /正在连接 n8n MCP/);
});

test("AI helper supports attachments and Enter-to-send", () => {
  const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
  assert.match(script, /AI_MCP_MAX_ATTACHMENTS\s*=\s*9/);
  assert.match(script, /AI_MCP_ATTACHMENT_ACCEPT/);
  assert.match(script, /data-ai-mcp-attach/);
  assert.match(script, /id="aiMcpAttachmentInput"/);
  assert.match(script, /multiple/);
  assert.match(script, /processAiMcpAttachments/);
  assert.match(script, /FileReader/);
  assert.match(script, /aiMcpAttachments/);
  assert.match(script, /renderAiMcpAttachments/);
  assert.match(script, /keydown/);
  assert.match(script, /event\.key === "Enter"/);
  assert.match(script, /!event\.shiftKey/);
  assert.match(script, /JSON\.stringify\(\{ messages: aiMcpMessages, attachments, workflowId: getActiveN8nWorkflowId\(\) \}\)/);
  assert.match(styles, /\.ai-mcp-attachments/);
  assert.match(styles, /\.ai-mcp-attach-button/);
  assert.doesNotMatch(script, /最多 9 个附件/);
  assert.doesNotMatch(styles, /\.ai-mcp-attachment-empty/);
  assert.match(server, /body\.attachments/);
  assert.match(server, /normalizeAiAttachments/);
  assert.match(server, /AI_MCP_MAX_ATTACHMENTS/);
  assert.match(server, /10_000_000/);
});

test("AI helper can inspect execution detail from pasted n8n logs before repairing workflows", () => {
  const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
  assert.match(server, /yunti_get_execution_detail/);
  assert.match(server, /normalizeExecutionDetail/);
  assert.match(server, /\/api\/n8n\/execution/);
  assert.match(server, /resultData/);
  assert.match(server, /runData/);
  assert.match(server, /nodeErrors/);
  assert.match(server, /extractExecutionIdFromText/);
  assert.match(server, /用户粘贴 n8n 执行日志/);
  assert.match(server, /webhook-test/);
  assert.match(server, /yunti_patch_workflow_nodes/);
});

test("mobile n8n page collapses the AI panel so the native canvas remains first", () => {
  assert.match(script, /innerWidth <= 1060/);
  assert.match(script, /ai-panel-collapsed/);
  assert.match(styles, /max-width: 760px/);
  assert.match(styles, /\.yunti-workflow-body\s*\{\s*display: grid/);
});

test("agent configuration exposes operator-facing submodules including answer execution testing", () => {
  assert.match(script, /agentConfigSubmodules/);
  assert.match(index, /agent-config-sidebar-subnav/);
  assert.match(index, /data-agent-config-route="workflow-build"/);
  assert.match(index, /data-agent-config-route="answer-test"/);
  assert.match(script, /工作流搭建/);
  assert.match(script, /销售技能/);
  assert.match(script, /智能标签/);
  assert.match(index, />资料中心</);
  assert.match(script, /资料中心/);
  assert.match(script, /renderKnowledgeBasePage/);
  assert.match(script, /renderKnowledgeResourceBuilder/);
  assert.match(script, /资源列表/);
  assert.match(script, /新建资源/);
  assert.match(script, /data-knowledge-resource-delete-document/);
  assert.match(script, /删除文档/);
  assert.match(script, /openKnowledgeResourceDeleteConfirm/);
  assert.match(script, /data-knowledge-resource-delete-confirm/);
  assert.match(script, /上传文件/);
  assert.match(script, /数据处理/);
  assert.match(script, /切片编辑/);
  assert.match(script, /openKnowledgeChunkDeleteConfirm/);
  assert.match(script, /closeKnowledgeChunkEdit/);
  assert.match(script, /knowledgeChunkEditGuardUntil/);
  assert.match(script, /renderKnowledgeChunkImageEditor/);
  assert.match(script, /if \(!chunk\.image && !chunk\.imageSrc\) return "";/);
  assert.match(script, /\$\{renderKnowledgeChunkImageEditor\(chunk\)\}/);
  assert.match(script, /isEditing \? "" : `\s*<div class="knowledge-chunk-actions"/);
  assert.match(script, /data-knowledge-chunk-edit="\$\{escapeHTML\(chunk\.id\)\}">编辑<\/button>/);
  assert.doesNotMatch(script, /data-knowledge-chunk-add="end">新增切片/);
  assert.doesNotMatch(script, /data-knowledge-chunk-edit="[^"]*">\$\{editingKnowledgeChunkId === chunk\.id \? "完成" : "编辑"\}<\/button>/);
  assert.doesNotMatch(script, /data-knowledge-chunk-edit="[^"]*">完成<\/button>/);
  assert.match(styles, /\.knowledge-resource-table/);
  assert.match(styles, /\.knowledge-upload-zone/);
  assert.match(styles, /\.knowledge-chunk-card/);
  assert.match(styles, /\.page-actions button\.danger-top/);
  assert.doesNotMatch(styles, /\.knowledge-chunk-card\.editing \.knowledge-chunk-actions/);
  assert.match(script, /执行测试/);
  assert.match(script, /答案来源追踪/);
  assert.match(script, /标注好坏回答/);
  assert.match(script, /学习回流/);
  assert.match(styles, /\.answer-test-shell\s*\{[\s\S]*height: 100vh;[\s\S]*overflow: hidden;/);
  assert.match(styles, /\.answer-dialog\s*\{[\s\S]*grid-template-rows: auto minmax\(0, 1fr\) auto;/);
  assert.match(styles, /\.answer-dialog-scroll\s*\{[\s\S]*overflow: auto;/);
  assert.match(index, /styles\.css\?v=/);
  assert.match(index, /data-agent-config-toggle/);
  assert.match(script, /toggleAgentConfigSubnav/);
  assert.match(styles, /\.agent-config-sidebar-subnav/);
  assert.match(styles, /\.agent-config-sidebar-subnav button\.active/);
  assert.match(styles, /\.agent-config-sidebar-subnav\.collapsed/);
  assert.match(styles, /\.nav-group\[data-agent-config-toggle\] > svg/);
  assert.match(styles, /background: #fff;/);
  assert.match(styles, /border: 1px solid #d4d9e4;/);
  assert.doesNotMatch(styles, /:has\(.n8n-ui-panel\)[^{]+\.sub-nav,[\s\S]*?display: revert !important/);
  assert.doesNotMatch(script, /agent-config-detail/);
  assert.doesNotMatch(styles, /\.agent-config-detail/);
});

test("agent configuration shell uses editable project name and a white workspace canvas", () => {
  assert.match(index, /data-section="get-started"[^>]*aria-label="首页"/);
  assert.match(index, />\s*首页\s*</);
  assert.match(script, /section === "get-started"/);
  assert.match(script, /routeToAgentOSHome/);
  assert.match(script, /section === "workspace"/);
  assert.match(script, /history\.replaceState\(null, "", "#agentos"\)/);
  assert.match(index, /data-agentos-tab="templates"/);
  assert.match(index, /data-agentos-tab="workspace"[^>]*>项目空间/);
  assert.match(index, /data-agentos-panel="templates"/);
  assert.match(index, /data-agentos-panel="workspace"/);
  assert.match(index, /data-agentos-project="yuanfudao"/);
  assert.match(script, /openAgentOSProject/);
  assert.match(script, /renderAgentConfigPage\(projectId === "yuanfudao" \? "sales-skills" : "workflow-build"\)/);
  assert.doesNotMatch(script, /已进入猿辅导课包项目空间/);
  assert.doesNotMatch(script, /已切换到项目空间/);
  assert.doesNotMatch(script, /已返回首页/);
  assert.doesNotMatch(script, /已折叠云梯智客侧栏/);
  assert.doesNotMatch(script, /已展开云梯智客侧栏/);
  assert.doesNotMatch(index, /workspace-home/);
  assert.doesNotMatch(index, /我的空间首页/);
  assert.doesNotMatch(script, /history\.replaceState\(null, "", "#workspace"\);\s*showHome\(\);/);
  assert.match(index, /<button class="brand-home-link"[^>]*>猿辅导课堂<\/button>/);
  assert.doesNotMatch(index, /<button class="brand-home-link"[^>]*>云梯智客<\/button>/);
  assert.doesNotMatch(index, /<button class="brand-home-link"[^>]*data-agentos-home[^>]*data-project-name-edit/);
  assert.match(index, /data-project-name-edit/);
  assert.match(styles, /body:not\(\.agentos-visible\) \.workspace\.page-open:not\(:has\(\.n8n-ui-panel\)\)\s*\{[\s\S]*background: #fff !important;/);
  assert.match(styles, /body:not\(\.agentos-visible\) \.workspace\.page-open:not\(:has\(\.n8n-ui-panel\)\)::before,[\s\S]*display: none !important;/);
});

test("sales skills page supports basic settings, searchable table, and create/edit/delete flows", () => {
  assert.match(script, /renderSalesSkillsPage/);
  assert.match(script, /salesSkillStore/);
  assert.match(script, /<h3>全局设定<\/h3>/);
  assert.doesNotMatch(script, /<span>基本设定<\/span>\s*<h3>全局规矩<\/h3>/);
  assert.doesNotMatch(script, /销售技能全局规则/);
  assert.match(script, /sales-basic-content/);
  assert.doesNotMatch(script, /data-sales-basic-edit/);
  assert.doesNotMatch(script, /data-sales-basic-pause/);
  assert.doesNotMatch(script, /data-sales-basic-delete/);
  assert.match(script, /data-sales-skill-search/);
  assert.match(script, /data-sales-skill-create/);
  assert.match(script, /data-sales-skill-row/);
  assert.match(script, /data-sales-skill-checkbox/);
  assert.match(script, /data-sales-skill-select-all/);
  assert.match(script, /data-sales-skill-bulk-action/);
  assert.match(script, /renderSalesSkillBulkActions/);
  assert.match(script, /data-sales-skill-bulk-action="activate"/);
  assert.match(script, /const hasActive = selectedSkills\.some\(\(skill\) => !skill\.paused\)/);
  assert.match(script, /const hasPaused = selectedSkills\.some\(\(skill\) => skill\.paused\)/);
  assert.match(script, /action === "activate"/);
  assert.match(script, /已激活选中技能/);
  assert.match(script, /共 \$\{salesSkillStore\.length\} 项/);
  assert.doesNotMatch(script, /\$\{filteredSkills\.length\} \/ \$\{salesSkillStore\.length\}/);
  assert.doesNotMatch(script, /data-sales-skill-cancel/);
  assert.doesNotMatch(script, /data-sales-skill-action="edit"/);
  assert.doesNotMatch(script, /data-sales-skill-action="pause"/);
  assert.doesNotMatch(script, /data-sales-skill-action="delete"/);
  assert.doesNotMatch(script, /sales-skill-row-actions/);
  assert.match(script, /名称/);
  assert.match(script, /适用条件/);
  assert.match(script, /技能描述/);
  assert.match(script, /## 处理目标/);
  assert.match(script, /## 执行步骤/);
  assert.match(script, /## 边界/);
  assert.match(script, /sales-skill-description-editor/);
  assert.match(script, /rows="12"/);
  assert.match(script, /创建时间/);
  assert.match(script, /openSalesSkillModal/);
  assert.match(script, /openSalesBasicModal/);
  assert.match(script, /saveSalesSkillFromModal/);
  assert.match(script, /selectSalesSkill/);
  assert.match(script, /deleteSalesSkill/);
  assert.match(script, /sort\(\(a, b\) => b\.createdAt - a\.createdAt\)/);
  assert.doesNotMatch(script, /技能描述或创建时间/);
  assert.doesNotMatch(script, /formatSkillTime\(skill\.createdAt\)\]\s*\.some/);
  assert.doesNotMatch(script, /已保存销售技能草稿/);
  assert.doesNotMatch(script, />保存草稿<\/button>/);
  assert.doesNotMatch(script, /<p>\$\{escapeHTML\(item\.desc\)\}<\/p>/);
  assert.match(styles, /\.sales-skills-workbench/);
  assert.match(styles, /\.sales-skill-table/);
  assert.doesNotMatch(styles, /\.sales-basic-actions/);
  assert.doesNotMatch(styles, /\.sales-skill-row-actions/);
  assert.match(styles, /\.sales-skill-cell-clamp/);
  assert.match(styles, /-webkit-line-clamp: 2/);
  assert.doesNotMatch(styles, /\.sales-skill-editor/);
  assert.match(styles, /\.sales-skill-modal-form/);
  assert.match(styles, /\.sales-skill-description-editor/);
  assert.match(styles, /min-height: 260px/);
  assert.match(styles, /ui-monospace/);
});

test("smart tags page lists categories, tag values, and stateful actions", () => {
  assert.match(script, /renderSmartTagsPage/);
  assert.match(script, /smartTagCategories/);
  assert.match(script, /selectedSmartTagCategoryId/);
  assert.match(script, />类别<\/span>/);
  assert.match(script, />标签<\/span>/);
  assert.match(script, /生效中标签数/);
  assert.match(script, /activeTags/);
  assert.doesNotMatch(script, /<div><span>已暂停<\/span>/);
  assert.match(script, /客户阶段/);
  assert.match(script, /购买意向/);
  assert.match(script, /咨询主题/);
  assert.match(script, /转人工规则/);
  assert.match(script, /骚扰处理/);
  assert.match(script, /新线索/);
  assert.match(script, /正在了解/);
  assert.match(script, /试听预约/);
  assert.match(script, /购买成交/);
  assert.match(script, /售后咨询/);
  assert.doesNotMatch(script, /smart-tag-table-panel/);
  assert.match(script, /expandedSmartTagCategoryIds/);
  assert.match(script, /data-smart-tag-category-toggle/);
  assert.match(script, /toggleSmartTagCategory/);
  assert.match(script, /smart-tag-home-table/);
  assert.match(script, /data-smart-tag-category-edit/);
  assert.match(script, /data-smart-tag-category-add/);
  assert.doesNotMatch(script, /<button data-smart-tag-category-add="\$\{escapeHTML\(category\.id\)\}"/);
  assert.match(script, /data-smart-tag-create/);
  assert.match(script, /openSmartTagCreateModal/);
  assert.match(script, /data-smart-tag-create-form/);
  assert.match(script, /data-smart-tag-create-row/);
  assert.match(script, /data-smart-tag-add-row/);
  assert.doesNotMatch(script, /data-smart-tag-remove-row/);
  assert.doesNotMatch(script, /smart-tag-create-row-remove/);
  assert.match(script, /name="returnCategoryId"/);
  assert.match(script, /添加一条标签/);
  assert.match(script, /smart-tag-editor-table-tools/);
  assert.match(script, /新增标签/);
  assert.match(script, /saveSmartTagCreateFromModal/);
  assert.match(script, /window\.__openSmartTagCreateModal/);
  assert.match(script, /window\.__addSmartTagCreateRow/);
  assert.match(script, /window\.__saveSmartTagCreateFromForm/);
  assert.match(script, /smartTagSubmitted/);
  assert.match(script, /标签类别<input name="categoryName"/);
  assert.match(script, /标签名称<input name="tagName"/);
  assert.match(script, /data-smart-tag-edit/);
  assert.match(script, /data-smart-tag-value="\$\{escapeHTML\(tag\.id\)\}" data-smart-tag-edit="\$\{escapeHTML\(tag\.id\)\}"/);
  assert.match(script, /openSmartTagCategoryModal/);
  assert.match(script, /resetSmartTagModalCloseButton/);
  assert.match(script, /renderSmartTagModalTitle/);
  assert.match(script, /data-smart-tag-modal-back/);
  assert.match(script, /saveSmartTagCategoryName/);
  assert.match(script, /openSmartTagDeleteConfirmModal/);
  assert.match(script, /commitSmartTagDelete/);
  assert.match(script, /data-smart-tag-delete-confirm/);
  assert.match(script, /data-smart-tag-delete-cancel/);
  assert.doesNotMatch(script, /confirmInlineSmartTagDelete/);
  assert.doesNotMatch(script, /确认删除";/);
  assert.match(script, /saveSmartTagCategoryFromModal/);
  assert.match(script, /data-smart-tag-category-modal-form/);
  assert.match(script, /data-smart-tag-modal-form/);
  assert.match(script, /data-smart-tag-category-name-input/);
  assert.match(script, /smart-tag-editor-table/);
  assert.match(script, /<th>名称<\/th><th>适用条件<\/th><th>创建时间<\/th><th class="smart-tag-actions-header" aria-label="类别操作"><\/th>/);
  assert.doesNotMatch(script, /<th>操作<\/th>/);
  assert.match(script, /<tr><th>名称<\/th><th>适用条件<\/th><th>创建时间<\/th><\/tr>/);
  assert.doesNotMatch(script, /class="smart-tag-category-condition"/);
  assert.doesNotMatch(script, /点击类别行展开或折叠标签/);
  assert.doesNotMatch(script, /modal-close\[data-smart-tag-back-category\]/);
  assert.doesNotMatch(script, />编辑标签类别<\/h3>/);
  assert.doesNotMatch(script, /先编辑类别名称，再在下方维护这个类别关联的特定标签/);
  assert.doesNotMatch(script, />保存<\/button>\s*<\/footer>\s*<\/form>\s*<section class="smart-tag-editor-table-panel"/);
  assert.match(script, /data-smart-tag-category-action="toggle/);
  assert.match(script, /data-smart-tag-category-action="delete/);
  assert.match(script, /data-smart-tag-action="toggle/);
  assert.match(script, /data-smart-tag-action="delete/);
  assert.match(script, /runSmartTagCategoryAction/);
  assert.match(script, /runSmartTagAction/);
  assert.match(script, /标签类别已暂停/);
  assert.match(script, /标签已激活/);
  assert.match(script, /if \(route === "smart-tags"\) return renderSmartTagsPage\(\)/);
  assert.match(styles, /\.smart-tag-layout/);
  assert.match(styles, /\.smart-tag-category/);
  assert.match(styles, /\.smart-tag-home-table/);
  assert.match(styles, /\.smart-tag-actions-header/);
  assert.match(styles, /\.smart-tag-create-button/);
  assert.match(styles, /\.smart-tag-create-editor/);
  assert.match(styles, /\.smart-tag-create-row/);
  assert.match(styles, /grid-template-columns: 1fr auto/);
  assert.match(styles, /\.smart-tag-create-row label:first-child/);
  assert.match(styles, /\.smart-tag-add-row-button/);
  assert.match(styles, /\.smart-tag-editor-table-tools/);
  assert.match(styles, /\.smart-tag-editor-table/);
  assert.match(styles, /\.smart-tag-modal-title-row/);
  assert.match(styles, /\.smart-tag-modal-back/);
  assert.match(styles, /\.smart-tag-delete-confirm/);
  assert.match(styles, /\.smart-tag-chevron/);
  assert.match(styles, /opacity: 0/);
  assert.match(styles, /\.smart-tag-editor-table tbody tr:hover \.smart-tag-row-actions/);
  assert.match(styles, /white-space: nowrap/);
  assert.match(styles, /\.smart-tag-value-editor \.sales-skill-modal-form footer/);
  assert.match(index, /script\.js\?v=/);
  assert.match(index, /styles\.css\?v=/);
});
